language: generic
script:
  - echo "Nothing"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c404cd1ce44c_key -iv $encrypted_c404cd1ce44c_iv -in secret.enc -out secret -d
  - eval "$(ssh-agent -s)"
  - chmod 600 secret
  - ssh-add secret
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
